services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file

    sirene-api.sirene_service:
        class: Aldaflux\SireneApiBundle\Service\SireneApiService
        public: true
        autowire: true
        autoconfigure: true
        arguments:
            $container: "@service_container"
    Aldaflux\SireneApiBundle\Service\SireneApiService: '@sirene-api.sirene_service'

    sirene-api.sirene_siret_service:
        class: Aldaflux\SireneApiBundle\Service\SireneSiretService
        public: true
        autowire: true
        autoconfigure: true
        arguments:
            $sireneService: "@sirene-api.sirene_service"
    Aldaflux\SireneApiBundle\Service\SireneSiretService: '@sirene-api.sirene_siret_service'


    sirene-api.data_collector:
        class: Aldaflux\SireneApiBundle\DataCollector\RequestCollector
        arguments: ["@sirene-api.sirene_service"]
        tags:
            -
                name:     data_collector
                template: '@AldafluxSireneApi/Collector/sirene_collector.html.twig'
                id:       'aldaflux_sirene_api.request_collector'
        public: false
        
 