services:
    sirene-api.sirene_service:
        class: Aldaflux\SireneApiBundle\Service\SireneApiService
        public: true
        autowire: true
        autoconfigure: true
        arguments:
            $container: "@service_container"
    Aldaflux\SireneApiBundle\Service\SireneApiService: '@sirene-api.sirene_service'


    sirene-api.data_collector:
        class: Aldaflux\SireneApiBundle\DataCollector\RequestCollector
        tags:
            -
                name:     data_collector
                template: '@AldafluxSireneApi/Collector/sirene_collector.html.twig'
                id:       'aldaflux_sirene_api.request_collector'
        public: false
        
 