services:
    pericles3.login.listener:
        class: Pericles3Bundle\Login\LoginListener
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: login }
 
    app.twig_extension:
        class: Pericles3Bundle\Twig\AppExtension
        public: false
        arguments:
          $em: "@doctrine.orm.entity_manager"
          $container: "@service_container"
          $context: "@security.token_storage"
        tags:
            - { name: twig.extension }

