 
in_da_flux_swiss_army_knife:
    resource: "@InDaFluxSwissArmyKnifeBundle/Controller/"
    type:     annotation
    prefix:   /

in_da_flux_html_to_doc_w_img:
    resource: "@InDaFluxHtmlToDocWImgBundle/Controller/"
    type:     annotation
    prefix:   /

in_da_flux_j_query_ui:
    resource: "@InDaFluxJQueryUIBundle/Controller/"
    type:     annotation
    prefix:   /


in_da_flux_fontello:
    resource: "@InDaFluxFontelloBundle/Controller/"
    type:     annotation
    prefix:   /

in_da_flux_table_triable:
    resource: "@InDaFluxTableTriableBundle/Controller/"
    type:     annotation
    prefix:   /

 
mobile_homepage:
    path:     /
    host:     ehpad.{domain}
    defaults: 
        _controller: Pericles3Bundle:FrontOffice/Index:ehpad 
        domain: '%domain%'
    requirements:
        domain: '%domain%'

        
pericles3_backoffice:
    resource: "@Pericles3Bundle/Controller/BackOffice"
    type:     annotation
     
pericles3_frontoffice:
    resource: "@Pericles3Bundle/Controller/FrontOffice"
    type:     annotation
 
 
      
gantt:
    resource: "@InDaFluxJQueryGanttBundle/Controller"
    type:     annotation

 
 
fados_chartjs:
    resource: "@ChartjsBundle/Resources/config/routing.xml"
    

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

