# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
    # garder votre nom de service court
#    htmltomht:
#        class: InDaFlux\HtmlToDocWImgBundle\Utils\HtmlToMht
#    saksimple:
#        class: InDaFlux\SwissArmyKnifeBundle\Utils\SAKSimple
    Utils:
        class: Pericles3Bundle\Utils\Utils
        arguments:
            $em: "@doctrine.orm.entity_manager"
            $container: "@service_container"
            $token_storage: "@security.token_storage"

#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


