<?php

namespace Pericles3Bundle\Repository;

/**
 * BibliothequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliothequeAncreaiTypeSourceRepository extends \Doctrine\ORM\EntityRepository
{

    
}
