<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\DemandeEtat;


/**
 * DemandeEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEtatRepository extends \Doctrine\ORM\EntityRepository
{ 
        
        
        
}
