<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Departement;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
 
        
        public function findByCreai($creai) 
        {
            $qb = $this->createQueryBuilder('departements');
            $qb->where("departements.creai= :creai");
            $qb->setParameter('creai', $creai);         
            return $qb->getQuery()->getResult();
        }
           
        
}
