<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Domaine;
/**
 * DimensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByDomaine(Domaine $domaine, $orderBy = null) {
		$qb = $this->createQueryBuilder('d');
		$qb->Join('d.referentiel', 'referentiel');
		$qb->where('d.domaine = :domaine_id')->setParameter('domaine_id', $domaine->getId());
		if (isset($orderBy))
			$qb->orderBy($orderBy);
		return $qb->getQuery()->getResult();
	}
}
