<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Etablissement;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByEtablissement(Etablissement $etablissement, $orderBy = null)
	{
		$qb = $this->createQueryBuilder('e');
		$qb->Join('e.referentiel', 'referentiel');
		$qb->where('e.etablissement = :etablissement_id')->setParameter('etablissement_id', $etablissement->getId());
		if (isset($orderBy))
			$qb->orderBy($orderBy);
		return $qb->getQuery()->getResult();
	}
       
        
            
        public function FindReferentielDesuet() 
        {
            $qb = $this->createQueryBuilder('domaine');
            $qb->Join('domaine.etablissement', 'domaine_etablissement');
            $qb->Join('domaine_etablissement.referentielPublic', 'domaine_referentielPublic');
            $qb->Join('domaine.referentiel', 'domaine_referentiel');
            $qb->Join('domaine_referentiel.ReferentielPublic', 'domaine_referentielPublic2');
            $qb->where("domaine_referentielPublic2.id <> domaine_referentielPublic.id");
            return $qb->getQuery()->getResult();
        }
        
        
        
        
}
