<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\DomaineExterne;
use Pericles3Bundle\Entity\Etablissement;
use Pericles3Bundle\Entity\ReferentielExterneNiv1;





/**
 * DomaineExterne
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineExterneRepository extends \Doctrine\ORM\EntityRepository
{
        
    public function findOneByEtabExtrneN1(Etablissement $etablissement, ReferentielExterneNiv1 $ReferentielExterneNiv1)
	{
		$qb = $this->createQueryBuilder('domexterne');
		$qb->Join('domexterne.etablissement', 'etablissement');
		$qb->where('etablissement.id = :etablissement_id');
		$qb->andWhere('domexterne.referentielExterneN1 = :refex_id');
                $qb->setParameter('etablissement_id', $etablissement->getId());
                $qb->setParameter('refex_id', $ReferentielExterneNiv1->getId());
//                return($qb->getQuery()->getResult());
                return($qb->getQuery()->getSingleResult());
                    
                
	}
    
    
    
        
}

