<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\EditorialPublication;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorialPublicationRepository extends \Doctrine\ORM\EntityRepository
{
 
        
}

