<?php

namespace Pericles3Bundle\Repository;


/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementCategoryRepository extends \Doctrine\ORM\EntityRepository
{
   
}
