<?php

namespace Pericles3Bundle\Repository;
use Pericles3Bundle\Entity\Creai;



/**
 * ReferentielPublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinessRepository extends \Doctrine\ORM\EntityRepository
{
        public function GetFirsts($limit=200) 
        {
                $qb = $this->createQueryBuilder('finess');
//              $qb->where('dimension.domaine= :domaine_id')->setParameter('domaine_id', $Domaine->getId());
                $qb->setMaxResults($limit);
		return $qb->getQuery()->getResult();
	}
        
/*        
        public function GetByCodePostal($limit=200) 
        {
                $qb = $this->createQueryBuilder('finess');
//              $qb->where('dimension.domaine= :domaine_id')->setParameter('domaine_id', $Domaine->getId());
                $qb->setMaxResults($limit);
		return $qb->getQuery()->getResult();
	}
 * 
 */
        
        
        
    public function findProspectionReferentielPublic(\Pericles3Bundle\Entity\ReferentielPublic $referentielPublic) 
    {
        $qb = $this->createQueryBuilder('finess');
        $qb->Join('finess.gestionnaire', 'finessGestionnaire');
        $qb->LeftJoin('finess.etablissement', 'etablissementArsene');
        $qb->Join('finessGestionnaire.gestionnaire', 'gestionnaireArsene');
        $qb->Join('finess.codeCategorie', 'categorie');
        $qb->Join('categorie.referentielPublicDefault', 'refpublic');
        $qb->Where('etablissementArsene.id is null and  refpublic.id = '.$referentielPublic->GetId());

//        $qb->where('category.reel=1 AND finess.codeCategorie ='.$finessCategorie->getId());
        return $qb->getQuery()->getResult();
    }
    
     
    public function findProspectionCreai(\Pericles3Bundle\Entity\Creai $creai) 
    {
        $qb = $this->createQueryBuilder('finess');
        $qb->Join('finess.gestionnaire', 'finessGestionnaire');
        $qb->LeftJoin('finess.etablissement', 'etablissementArsene');
        $qb->Join('finessGestionnaire.gestionnaire', 'gestionnaireArsene');
        $qb->Join('finess.departement', 'etabDepartement');
        $qb->Join('etabDepartement.creai', 'etabCreai');
        $qb->Join('gestionnaireArsene.creai', 'gestionnaireCreai');
        
        $qb->Where('etablissementArsene.id is null ');
        $qb->AndWhere('etabCreai.id = '.$creai->GetId().'or gestionnaireCreai.id = '.$creai->GetId());
        
//        $qb->Where('etablissementArsene.id is null and  creai.id = '.$creai->GetId());
        return $qb->getQuery()->getResult();
    }
    
            
        public function findSupprimerDansImport() 
        {
                $qb = $this->createQueryBuilder('anciens');
                $qb->leftJoin('Pericles3Bundle:FinessImport', 'nouveaux', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('nouveaux.codeFiness IS NULL');
		return $qb->getQuery()->getResult();
	}
        
            
        public function findSupprimerDansImportAvecEtablissement() 
        {
                $qb = $this->createQueryBuilder('anciens');
                $qb->InnerJoin('anciens.etablissement', 'etablissementArsene');
                $qb->leftJoin('Pericles3Bundle:FinessImport', 'nouveaux', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('nouveaux.codeFiness IS NULL');
		return $qb->getQuery()->getResult();
	}
        
        public function findSupprimerDansImportAvecDemande() 
        {
                $qb = $this->createQueryBuilder('anciens');
                $qb->InnerJoin('anciens.demandesEtablissement', 'demande');
                $qb->leftJoin('Pericles3Bundle:FinessImport', 'nouveaux', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('nouveaux.codeFiness IS NULL');
		return $qb->getQuery()->getResult();
	}
        
        public function findSupprimerDansImportAvecPericles() 
        {
                $qb = $this->createQueryBuilder('anciens');
                $qb->InnerJoin('anciens.pericles', 'pericles');
                $qb->leftJoin('Pericles3Bundle:FinessImport', 'nouveaux', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('nouveaux.codeFiness IS NULL');
		return $qb->getQuery()->getResult();
	}
        
        
        
        public function findImportDifferentEtablissement() 
        {
                $qb = $this->createQueryBuilder('anciens');
                $qb->select('etablissementArsene.id as etablissement_id, etablissementArsene.nom as etablissementRaisonSociale, anciens.raisonSociale as oldRaisonSociale','nouveaux.raisonSociale as newRaisonSociale','anciens.ville as oldVille','nouveaux.ville as newVille');
                $qb->InnerJoin('anciens.etablissement', 'etablissementArsene');
                $qb->InnerJoin('Pericles3Bundle:FinessImport', 'nouveaux', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('anciens.ville <> nouveaux.ville ');
                $qb->OrWhere('anciens.raisonSociale<> nouveaux.raisonSociale AND etablissementArsene.nom <> nouveaux.raisonSociale ');
		return $qb->getQuery()->getResult();
	}
        
        
        
          
        public function findLike($occurence) 
        {
            $qb = $this->createQueryBuilder('etab');
            $qb->where("etab.raisonSociale LIKE :occurence or etab.codeFiness LIKE :occurence")->setParameter('occurence',"%".$occurence."%");
            $qb->setMaxResults(2);
            return $qb->getQuery()->getResult();
        }
        
        public function findLikeCreai($occurence, $creai) 
        {
            $qb = $this->createQueryBuilder('etab');
            $qb->select('etab.codeFiness ,departement.id ,etab.raisonSociale, CASE WHEN  creai.id='.$creai->GetId().' THEN 1 ELSE 0 END  as creai_match');
            $qb->LeftJoin('etab.departement', 'departement');
            $qb->LeftJoin('departement.creai', 'creai');
            $qb->where("etab.raisonSociale LIKE :occurence or etab.codeFiness LIKE :occurence")->setParameter('occurence',"%".$occurence."%");
            $qb->orderBy('creai_match', 'DESC');
            $qb->addOrderBy('etab.codeFiness', 'ASC');
            $qb->setMaxResults(20);
            return $qb->getQuery()->getResult();
        }
         

        
        
}
