<?php

namespace Pericles3Bundle\Repository;

/**
 * GestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinessGestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
         
          
        public function findLike($occurence) 
        {
            $qb = $this->createQueryBuilder('gestionnaire');
            $qb->where("gestionnaire.raisonSociale LIKE :occurence or gestionnaire.codeFiness LIKE :occurence")->setParameter('occurence',"%".$occurence."%");
            $qb->setMaxResults(20);
            return $qb->getQuery()->getResult();
        }
        
        
        
        
}
