<?php

namespace Pericles3Bundle\Repository;

/**
 * ReferentielPublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinessGestionnaireImportRepository extends \Doctrine\ORM\EntityRepository
{
   
        public function findNouveaux() 
        {
                $qb = $this->createQueryBuilder('nouveaux');
                $qb->leftJoin('Pericles3Bundle:FinessGestionnaire', 'anciens', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('anciens.codeFiness IS NULL');
		return $qb->getQuery()->getResult();
	}
        
        
        public function findCommuns() 
        {
                $qb = $this->createQueryBuilder('nouveaux');
                $qb->Join('Pericles3Bundle:FinessGestionnaire', 'anciens', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
		return $qb->getQuery()->getResult();
	}
        
        
    
    
}
