<?php

namespace Pericles3Bundle\Repository;

/**
 * ReferentielPublicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinessImportRepository extends \Doctrine\ORM\EntityRepository
{
        public function findFirsts($limit=200) 
        {
                $qb = $this->createQueryBuilder('finess_import');
//              $qb->where('dimension.domaine= :domaine_id')->setParameter('domaine_id', $Domaine->getId());
                $qb->setMaxResults($limit);
		return $qb->getQuery()->getResult();
	}
        
        public function findNouveaux() 
        {
                $qb = $this->createQueryBuilder('nouveaux');
                $qb->leftJoin('Pericles3Bundle:Finess', 'anciens', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
                $qb->Where('anciens.codeFiness IS NULL');
		return $qb->getQuery()->getResult();
	}
        
        
        public function findCommuns() 
        {
                $qb = $this->createQueryBuilder('nouveaux');
                $qb->Join('Pericles3Bundle:Finess', 'anciens', 'WITH', 'nouveaux.codeFiness= anciens.codeFiness');
		return $qb->getQuery()->getResult();
	}
        
        
    
    
}
