<?php

namespace Pericles3Bundle\Repository;
 
/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeCotisationRepository extends \Doctrine\ORM\EntityRepository
{
    
     
        
        
}
