<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Etablissement;
use Pericles3Bundle\Entity\Patch;


/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchToDoBatchRepository extends \Doctrine\ORM\EntityRepository
{
	 
     
    
    public function findToDo() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateDebutPatch IS NULL" );
        return $qb->getQuery()->getResult();
    }	
    
    
    public function findEnCours() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateFinPatch IS NULL" );
        $qb->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    
    
    
    
    public function findDone() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateFinPatch IS NOT NULL" );
        return $qb->getQuery()->getResult();
    }	
    
    
    
    
    
        
}
