<?php

namespace Pericles3Bundle\Repository;
 
/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchToDoRepository extends \Doctrine\ORM\EntityRepository
{
	 
    
    
    public function findDefault() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateFinPatch IS NULL OR patchToDo.dateFinPatch>'".date("Y-m-d")."'" );
        return $qb->getQuery()->getResult();
    }	
    
    
    public function findToDo() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateDebutPatch IS NULL" );
        return $qb->getQuery()->getResult();
    }	
    
    public function findDone() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateFinPatch IS NOT NULL" );
        return $qb->getQuery()->getResult();
    }	
    
    
    
    
    
        
}
