<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Etablissement;
use Pericles3Bundle\Entity\Patch;


/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchToDoRepository extends \Doctrine\ORM\EntityRepository
{
	 
    
    
    public function findDefault() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateFinPatch IS NULL OR patchToDo.dateFinPatch>'".date("Y-m-d")."'" );
        return $qb->getQuery()->getResult();
    }	
    
    
    public function findToDo() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateDebutPatch IS NULL" );
        return $qb->getQuery()->getResult();
    }	
    
    public function findToDoEtablissementPatch(Etablissement $etablissement, Patch $patch) 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateDebutPatch IS NULL and patchToDo.etablissement=".$etablissement->GetId()." and patchToDo.patch=".$patch->GetId());
        return  $qb->getQuery()->getOneOrNullResult();
    }	
    
    public function findDone() 
    {
        $qb = $this->createQueryBuilder('patchToDo');
        $qb->Where("patchToDo.dateFinPatch IS NOT NULL" );
        return $qb->getQuery()->getResult();
    }	
    
    
    
    
    
        
}
