<?php

namespace Pericles3Bundle\Repository;
 
/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatchRepository extends \Doctrine\ORM\EntityRepository
{
	 
    
    public function findWithSource(\Pericles3Bundle\Entity\ReferentielPublic $Source) 
    {
        $qb = $this->createQueryBuilder('patch');
        $qb->Where("patch.patcheRefPublicSource = ".$Source->GetId());
        return $qb->getQuery()->getResult();
    }	
    
        
}


