<?php

namespace Pericles3Bundle\Repository;

 

/**
 * PreuveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilesRolesRepository extends \Doctrine\ORM\EntityRepository
{

    	public function findRolesEtablissement() 
        {
            $qb = $this->createQueryBuilder('roles');
            $qb->where("roles.TypeUser='ETABLISSEMENT'"); 
            return $qb->getQuery()->getResult();
	}           
        
 	public function findRolesGestionnaire() 
        {
            $qb = $this->createQueryBuilder('roles');
            $qb->where("roles.TypeUser='GESTIONNAIRE'"); 
            return $qb->getQuery()->getResult();
	}
        
 	public function findRolesEtablissementAdmin() 
        {
            $qb = $this->createQueryBuilder('roles');
            $qb->where("roles.id=1"); 
            return $qb->getQuery()->getResult();
	}
        
    
}


    
    	