<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\BibliothequeAncreai;
use Pericles3Bundle\Entity\Dimension;
use Pericles3Bundle\Entity\Domaine;
use Pericles3Bundle\Entity\Etablissement;
/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualiEvalReferentielRepository extends \Doctrine\ORM\EntityRepository
{
        public function findN1() 
        {
		$qb = $this->createQueryBuilder('qe');
		$qb->join('qe.niveau', "niveau");
		$qb->where('niveau.id= 1');
		$qb->OrderBy('qe.ordre');
		return $qb->getQuery()->getResult();
	}
        
}
