<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Critere;
/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByCritere(Critere $critere, $orderBy = null) {
		$qb = $this->createQueryBuilder('c');
		$qb->Join('c.referentiel', 'referentiel');
		$qb->where('c.critere = :critere_id')->setParameter('critere_id', $critere->getId());
		if (isset($orderBy))
			$qb->orderBy($orderBy);
		return $qb->getQuery()->getResult();
	}
}
