<?php

namespace Pericles3Bundle\Repository;

/**
 * ReferentielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentielExterneRepository extends \Doctrine\ORM\EntityRepository
{
     

/*    
   SELECT DISTINCT referentiel_externe.id as refId1, referentiel_externe .nom, referentiel_public.short , referentiel_externe_niv1.referentiel_externe_id as refId2 
 * FROM referentiel_externe 
 *      INNER JOIN referentiel_public ON referentiel_externe.id = referentiel_public.referentiel_externe_id 
 *      INNER JOIN etablissement on referentiel_public.id = etablissement.id 
 *      inner join `domaine_externe` on etablissement.id = domaine_externe.etablissement_id 
 *      INNER JOIN referentiel_externe_niv1 ON domaine_externe.referentiel_externe_n1_id = referentiel_externe_niv1.id 
 *      WHERE referentiel_externe.id<> referentiel_externe_niv1.referentiel_externe_id 
  
 *   
 * SELECT DISTINCT referentiel_externe.id as refId1, referentiel_externe.nom   FROM referentiel_externe INNER JOIN referentiel_public ON referentiel_externe.id = referentiel_public.referentiel_externe_id INNER JOIN etablissement on referentiel_public.id = etablissement.id   WHERE etablissement.id =41
 * 
 * 
 */                          
    
    public function  referentielsExternePasBon()
    {
         $qb = $this->createQueryBuilder('referentielExterne');
         $qb->Select('etablissements.nom, referentielExterne.id as id_1', 'referentielExterne.nom as nom_1','referentielExterne2.id as id_2', 'referentielExterne2.nom as nom_2');
         $qb->Join('referentielExterne.referentielPublic', 'referentielPublic_1');
         $qb->Join('referentielPublic_1.etablissements', 'etablissements');
         $qb->Join('etablissements.domainesExterne', 'domainesExterne');
         $qb->Join('domainesExterne.referentielExterneN1', 'referentielExterneN1');
         $qb->Join('referentielExterneN1.referentielExterne', 'referentielExterne2');
         $qb->where('referentielExterne.id<> referentielExterne2.id');
         return $qb->getQuery()->getResult();
        
    }
            
        
}
