<?php

namespace Pericles3Bundle\Repository;

/**
 * ReferentielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentielExterneNiv1Repository extends \Doctrine\ORM\EntityRepository
{
     
        public function findLike($occurence) 
        {
            $qb = $this->createQueryBuilder('t');
            $qb->where("t.nom LIKE :occurence or t.numero LIKE :occurence ")->setParameter('occurence',"%".$occurence."%");
//            $qb->where("t.nom LIKE :occurence")->setParameter('occurence',"%".$occurence."%");
            $qb->setMaxResults(20);
            return $qb->getQuery()->getResult();
        }    
    
    
}
