<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\Sauvegarde;
use Pericles3Bundle\Entity\Gestionnaire;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SauvegardeRepository extends \Doctrine\ORM\EntityRepository
{

        public function findByGestionnaire(\Pericles3Bundle\Entity\User $User) 
        {
		$qb = $this->createQueryBuilder('sauvegarde');
                $qb->Join('sauvegarde.etablissement', 'etablissement');
                
                if ($User->getIsAdminPole())
                  {
                      $qb->Join('etablissement.userPole', 'userPole');
                      $qb->where('userPole.id = :user_id')->setParameter('user_id', $User->getId());
                  }
                  else
                  {
                      $qb->where("etablissement.gestionnaire = :gestionnaire_id")->setParameter('gestionnaire_id', $User->getGestionnaire()->getId());
                  }
 
//                $qb->where('gestionnaire = :gestionnaire_id')->setParameter('gestionnaire_id', $gestionnaire->getId());
		return $qb->getQuery()->getResult();
                $qb->orderBy('sauvegarde.dateCreate DESC');
	}
        
        
        public function findOldCorbeille() 
        {
		$qb = $this->createQueryBuilder('sauvegarde');
                $qb->where("sauvegarde.deletedAt IS NOT NULL");
		return $qb->getQuery()->getResult();
	}
        
        public function findNotOldCorbeille() 
        {
		$qb = $this->createQueryBuilder('sauvegarde');
                $qb->where("sauvegarde.deletedAt  NULL");
		return $qb->getQuery()->getResult();
	}
         
        
        
        
}
