<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\SauvegardeDimension;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SauvegardeDimensionRepository extends \Doctrine\ORM\EntityRepository
{
        
        
}
