<?php

namespace Pericles3Bundle\Repository;

use Pericles3Bundle\Entity\SauvegardeDomaine;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SauvegardeDomaineRepository extends \Doctrine\ORM\EntityRepository
{
        
        
}
