<?php

namespace Pericles3Bundle\Repository;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatUserConnectRepository extends \Doctrine\ORM\EntityRepository
{
     
        
        
        
}
