<?php

namespace Pericles3Bundle\Repository;
 
use Pericles3Bundle\Entity\StockageEtablissement;
/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockageEtablissementRepository extends \Doctrine\ORM\EntityRepository
{ 
        
}
