<?php

namespace Pericles3Bundle\Repository;

/**
 * TypeReferentielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeReferentielRepository extends \Doctrine\ORM\EntityRepository
{
}
